name: Lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  lint_test:
    name: Python ${{ matrix.python_version }} lint test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ "3.7", "3.8", "3.9" ]
    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Update Dependencies
        run: |
          pip install virtualenv
          virtualenv test_python -q
          source test_python/bin/activate
          make installdeps-dev
      - name: Run Lint Test
        run: |
          source test_python/bin/activate
          make lint
      - name: Notify on Slack
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # MATRIX_CONTEXT: ${{ toJson(matrix) }}
        with:
          status: custom
          job_name: Python ${{ matrix.python_version }} lint test
          fields: workflow,commit,job,repo,ref,author
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        if: always() # Pick up events even if the job fails or is canceled.
