name: Unit tests, linux, min dependencies

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  unit_tests:
    name: ${{ matrix.python_version }} min dep ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.7']
        command: ['git-test-automl', 'git-test-modelunderstanding', 'git-test-other', 'git-test-dask']
    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 2
      - name: Update apt and install Graphviz
        run: sudo apt update && sudo apt install -y graphviz
      - name: Create virtual environment, upgrade pip
        run: |
          pip install virtualenv
          virtualenv test_python -q
          source test_python/bin/activate
          python -m pip install --upgrade pip -q
      - name: install evalml with test dependencies, core dependencies, & optional requirements
        run: |
          source test_python/bin/activate
          pip install -e . --no-dependencies
          pip install -r evalml/tests/dependency_update_check/minimum_test_requirements.txt
          pip install -r evalml/tests/dependency_update_check/minimum_core_requirements.txt
          pip install -r evalml/tests/dependency_update_check/minimum_requirements.txt
      - name: run tests
        run: |
          source test_python/bin/activate
          make ${{ matrix.command }}
      - name: Notify on Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${ matrix } ${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always() # Pick up events even if the job fails or is canceled.
