name: Nightly unit tests, linux

on:
  schedule:
      - cron: '0 7 * * *'

jobs:
  unit_tests:
    name: Nightly ${{ matrix.python_version }} ${{matrix.command}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.7', '3.8', '3.9']
        command: ['git-test-automl', 'git-test-modelunderstanding', 'git-test-other', 'git-test-dask']
    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: main
      - name: Update apt and install Graphviz
        run: sudo apt update && sudo apt install -y graphviz
      - name: Create virtual environment, upgrade pip
        run: |
          pip install virtualenv
          virtualenv test_python -q
          source test_python/bin/activate
          python -m pip install --upgrade pip -q
      - name: Installing Latest Dependency Versions
        run: |
          source test_python/bin/activate
          make installdeps
          make installdeps-test
          pip freeze
      - name: Run unit tests
        run: |
          source test_python/bin/activate
          make ${{matrix.command}}
  notify:
    name: Notify on Slack
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          github_base_url: https://github.com/alteryx/evalml
          status: ${{ job.status }}
          fields: repo,message,action,eventName,ref,workflow,job,took
          text: 'Linux Nightly Tests'
          mention: 'here'
          if_mention: 'failure,cancelled'
        if: always()
